add monolith miner instructions for indexer
filecoin-project/lotus-docs pull request #165
Opened 2022-04-18 14:32 UTC by LexLuthr

Based on 
https://github.com/filecoin-project/lotus/discussions/8341#discussioncomment-2544837

2022-04-18 15:19 UTC, LexLuthr commented on content/en/storage-providers/operate/index-provider.md
> +       lotus-miner --call-on-markets log set-level --system provider/engine --system go-legs-gpubsub --system dagstore info
```suggestion
       lotus-miner log set-level --system provider/engine --system go-legs-gpubsub --system dagstore info
```

2022-04-19 15:13 UTC, johnnymatthews requested changes
Can you remove the bolding `**` from each list item please. Otherwise, this PR is good to go!

2022-04-19 15:28 UTC, johnnymatthews approved these changes

2022-04-19 15:29 UTC, johnnymatthews commented
Nice! Thanks for that fix @LexLuthr. Merge when ready :)

2022-04-19 15:30 UTC, merged