feat: curio docker devnet
filecoin-project/lotus-docs pull request #727
Opened 2024-05-03 08:07 UTC by LexLuthr

Add instructions on how to create devnet images and spin of a docker devnet for Curio.

2024-05-03 08:09 UTC, Reiers approved these changes
LGTM

2024-05-06 11:21 UTC, Reiers requested changes

2024-05-06 11:21 UTC, Reiers commented on content/en/storage-providers/curio/local-network.md
> +   make curio-devnet/up
"sudo make curio-devnet/up" - it needs sudo to work.

2024-05-06 11:21 UTC, Reiers commented on content/en/storage-providers/curio/local-network.md
> +   make curio-devnet/down
"sudo make curio-devnet/up" - it needs sudo to work.

2024-05-07 10:32 UTC, Reiers commented
We don't need "sudo" - my local docker was the issue

2024-05-07 15:20 UTC, snadrus approved these changes

2024-05-08 10:18 UTC, Reiers approved these changes
Had my Infra test on their machines 👍 This guide is good 💯

2024-05-08 10:20 UTC, merged